name: gollum
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - astropy
  - astroquery
  - specutils # Manually install the dev version from GitHub
  - tqdm
  - pandas
  - bokeh
  - jupyter
  - ipython
  - seaborn
  - pytest
  - sphinx # for documentation and testing
  - nbsphinx # for documentation and testing
  - numpydoc # for documentation and testing
  - sphinx-automodapi # for documentation and testing
  - black
  - isort
  - tox
  - twine
  - pip
  - pip:
      - sphinx-material
