name: gollumtests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10.9, 3.11]
        specutils-version: [1.8, 1.11, 1.14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: OttoStruve/muler_example_data
          path: tests/data
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
      - name: Lint with flake8
        run: |
          uv run --with flake8 --with specutils==${{ matrix.specutils-version }} --extra test --extra docs \
            flake8 src tests setup.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # stop the build if there are Python syntax errors or undefined names
          uv run --with flake8 --with specutils==${{ matrix.specutils-version }} --extra test --extra docs \
            flake8 src tests setup.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      - name: Test PHOENIX
        run: |
          uv run --with specutils==${{ matrix.specutils-version }} --extra test --extra docs \
            python -c "import sys; print(f'Python version: {sys.version}')"
          uv run --with specutils==${{ matrix.specutils-version }} --extra test --extra docs \
            python -c "import specutils; print(f'specutils version: {specutils.__version__}')"
          uv run --with specutils==${{ matrix.specutils-version }} --extra test --extra docs \
            python -c "import astropy; print(f'astropy version: {astropy.__version__}')"
          uv run --with specutils==${{ matrix.specutils-version }} --extra test --extra docs \
            pytest tests/test_phoenix.py
      - name: Test Precomputed
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 5
          retry_on: error
          warning_on_retry: false
          command: uv run --with specutils==${{ matrix.specutils-version }} --extra test --extra docs pytest tests/test_precomputed.py
